disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_comma
  - vertical_whitespace
  - trailing_whitespace
  - line_length
  - force_try
  - identifier_name
  - nesting
opt_in_rules:
  - empty_count
  - closing_brace
  - opening_brace
  - return_arrow_whitespace
  - trailing_semicolon
  - statement_position
line_length: 110
type_body_length:
  warning: 300
  error: 1000
excluded:
  - Pods
  - Podfile
  - Podfile.lock
reporter: "xcode"
warning_threshold: 25